[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile.railway"

[deploy]
numReplicas = 1
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[deploy.env]
PORT = "3000" 