#!/bin/bash

set -e

echo "========================================"
echo "🚀 Starting Fluida Frontend (Dev Mode)"
echo "========================================"

# Check if .env file exists at the root level, otherwise create from example
if [ ! -f .env ]; then
  echo "🔧 Creating root .env file from .env.example..."
  cp .env.example .env
  echo "✅ Root .env file created. You may want to review and update it."
else
  echo "✅ Using existing root .env file"
fi

# Load environment variables from root .env file
echo "🔧 Loading environment variables from root .env file..."
eval "$(grep -v '^#' .env | sed 's/^/export /')"

# Change directory to frontend
cd frontend

echo "📦 Installing dependencies..."
npm install || npm install --legacy-peer-deps

# Create a local .env file that links to the root variables
# (this is needed because Next.js expects .env file in its directory)
echo "🔧 Creating local .env file with variables from root .env..."
echo "# This file is automatically generated from root .env" > .env
echo "NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL" >> .env
echo "NODE_ENV=development" >> .env

echo "🔥 Starting development server..."
npm run dev

# Note: Dev server will keep running until terminated with Ctrl+C 