services:
  # Database
  db:
    image: postgres:15-alpine
    container_name: fluida-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - fluida-network
    restart: unless-stopped

  # Backend API
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: fluida-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: ${POSTGRES_PORT}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      PORT: ${BACKEND_PORT}
      API_VERSION: ${API_VERSION}
      ENVIRONMENT: ${ENVIRONMENT:-production}
      DEBUG: ${DEBUG:-false}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable
      AUTH_USERNAME: ${AUTH_USERNAME:-admin}
      AUTH_PASSWORD: ${AUTH_PASSWORD:-fluida}
    ports:
      - "${BACKEND_PORT}:8080"
    volumes:
      - ./backend:/app
    networks:
      - fluida-network
    restart: unless-stopped

  # Frontend web application
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fluida-frontend
    depends_on:
      - backend
    environment:
      NODE_ENV: ${NODE_ENV}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NEXT_PUBLIC_AUTH_USERNAME: ${AUTH_USERNAME:-admin}
      NEXT_PUBLIC_AUTH_PASSWORD: ${AUTH_PASSWORD:-fluida}
    ports:
      - "${FRONTEND_PORT}:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - fluida-network
    restart: unless-stopped

# Persistent volumes
volumes:
  db_data:
    name: fluida-db-data

# Shared networks
networks:
  fluida-network:
    name: fluida-network 