[phases.setup]
nixpkgs = ["nodejs", "go", "postgresql", "curl"]

[phases.install]
cmds = [
  "cd frontend && npm ci",
  "cd backend && go mod download"
]

[phases.build]
cmds = [
  "cd frontend && npm run build",
  "cd backend && go build -o app"
]

[start]
cmd = "chmod +x railway-startup.sh && ./railway-startup.sh"

[deploy]
numReplicas = 1
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10 