[phases.setup]
nixpkgs = ["curl", "postgresql", "netcat", "python3"]

[phases.prepare]
cmds = [
  "curl -fsSL https://deb.nodesource.com/setup_20.x | bash -",
  "apt-get update",
  "apt-get install -y nodejs netcat",
  "npm --version && node --version",
  "curl -L https://go.dev/dl/go1.21.0.linux-amd64.tar.gz -o go.tar.gz && tar -C /usr/local -xzf go.tar.gz && export PATH=$PATH:/usr/local/go/bin && /usr/local/go/bin/go version"
]

[env]
PATH = "/usr/local/go/bin:${PATH}"
NODE_ENV = "production"

[phases.install]
cmds = [
  "cd backend && /usr/local/go/bin/go mod download"
]

[phases.build]
cmds = [
  # Frontend build with improved TailwindCSS installation
  "cd frontend && rm -rf node_modules .next",
  "cd frontend && npm ci",
  # Install TailwindCSS globally to ensure it's available for build
  "npm install -g tailwindcss postcss autoprefixer",
  # Install TailwindCSS locally to ensure it's available for Next.js build
  "cd frontend && npm install --no-save tailwindcss postcss autoprefixer @tailwindcss/forms",
  # Verify tailwind is installed correctly
  "cd frontend && ls -la node_modules/tailwindcss || echo 'TailwindCSS not found'",
  # Run the build with verbose output
  "cd frontend && NODE_ENV=production npm run build",
  # Backend build
  "cd backend && /usr/local/go/bin/go build -o app ./cmd/server"
]

[start]
cmd = "chmod +x railway-startup.sh && ./railway-startup.sh" 