name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    # Skip this job if it's a PR and we've already run the tests on the source branch
    if: github.event_name != 'pull_request' || !startsWith(github.head_ref, 'development')
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
          
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          
      - name: Install frontend dependencies
        run: cd frontend && npm ci
        
      - name: Lint frontend
        run: cd frontend && npm run lint
        
      - name: Build frontend
        run: cd frontend && npm run build
        
      - name: Test backend
        run: cd backend && go test ./...

  deploy-backend:
    name: Deploy Backend to Railway
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Install Railway CLI
        run: npm install -g @railway/cli
        
      - name: Deploy Backend to Railway
        run: cd backend && railway up --environment=production --detach
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
  
  deploy-frontend:
    name: Deploy Frontend to Railway
    runs-on: ubuntu-latest
    needs: [test, deploy-backend]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Install Railway CLI
        run: npm install -g @railway/cli
        
      - name: Deploy Frontend to Railway
        run: cd frontend && railway up --environment=production --detach
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }} 